require:
 - rubocop-performance
 - rubocop-rspec
 - rubocop-rake

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Metrics/BlockLength:
  Max: 36
  Exclude:
    - spec/**/*.rb
    - lokalise_manager.gemspec

RSpec/MultipleExpectations:
  Max: 10

RSpec/ExampleLength:
  Max: 35

RSpec/NestedGroups:
  Max: 4

RSpec/MultipleMemoizedHelpers:
  Max: 10

Metrics/AbcSize:
  Max: 18